<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var Template $block */
/** @var EntityFieldSelectInterface $element */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var MagewireFormComponent $magewire */

use Hyva\Checkout\Model\Form\EntityFieldSelectInterface;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magewirephp\Magewire\Component\Form as MagewireFormComponent;

$element = $block->getData('element');
$showLabel = $block->getData('show_label') ?: false;
$attributes = $element->getAttributes();
?>
<div class="block <?= $element->isRequired() ? 'required' : 'not-required' ?>">
    <?php if ($showLabel): ?>
        <?= /* @noEscape */ $element->getRenderer()->renderLabel($element) ?>
    <?php endif; ?>
    <?= /* @noEscape */ $element->getRenderer()->renderBefore($element) ?>

    <?php if ($element->hasRelatives()): ?>
    <div class="space-y-2">
        <?php endif ?>

        <div class="flex flex-wrap gap-2">
            <?php foreach ($element->getOptions() as $option): ?>
                <div>
                    <label class="p-2 bg-white border rounded-lg cursor-pointer text-sm font-bold
                                  <?= ($magewire->getAddress()['customer_type'] === $option['value']) ? 'border-blue-600 text-blue-600 checked' : 'border-secondary text-secondary' ?>">
                        <input type="radio"
                               class="hidden"
                               value="<?= $escaper->escapeHtml($option['value']) ?>"
                                <?php if ($element->hasAttributes()): ?>
                                    <?= /* @noEscape */ $element->renderAttributes($escaper) ?>
                                <?php endif ?>
                        />
                        <span><?= $escaper->escapeHtml($option['label']) ?></span>
                    </label>
                </div>
            <?php endforeach; ?>
        </div>

        <?php if ($element->hasRelatives()): ?>
            <?php foreach ($element->getRelatives() as $relative): ?>
                <?= /* @noEscape */ $relative->render() ?>
            <?php endforeach ?>
        <?php endif ?>

        <?php if ($element->hasRelatives()): ?>
    </div>
<?php endif ?>

    <?= /* @noEscape */ $element->getRenderer()->renderAfter($element) ?>
</div>
